#pragma once

typedef enum RC_t {
    UNINITIALIZED = -1,
    SUCCESS,
    FILE__OPEN__NULL_ARGUMENT,
    FILE__OPEN__FOPEN_ERROR,
    FILE__CLOSE__NULL_ARGUMENT,
    FILE__READ_LINE__NULL_ARGUMENT,
    FILE__READ_LINE__EOF_REACHED,
    FILE__READ_LINE__FGETS_ERROR,
    TEXT_EDITOR__REMOVE_SPACES_AND_TABS_FROM_LINE__NULL_ARGUMENT,
    TEXT_EDITOR__REMOVE_SPACES_AND_TABS_FROM_FILE__NULL_ARGUMENT,
    TEXT_EDITOR__REMOVE_SPACES_AND_TABS_IN_GIVEN_PATH__NULL_ARGUMENT,
    TEXT_EDITOR__REMOVE_SPACES_AND_TABS_NEAR_COMMA__NULL_ARGUMENT,
    MCRO_READER__READ_MCROS_FROM_FILE__NULL_ARGUMENT,
    MCRO_READER__EXTRACT_MCRO_NAME__NULL_ARGUMENT,
    MCRO_READER__MAX_MCROS_EXCEEDED,
    MCRO_READER__INVALID_MCRO_START_DEFINITION,
    MCRO_READER__INVALID_MCRO_END_DEFINITION,
    MCRO_READER__INVALID_MCRO_NAME,
    MCRO_READER__CONVERT_MCROS_TO_INSTRUCTIONS__NULL_ARGUMENT,
    ARCHITECTURE__GET_OPCODE_DETAILS__NULL_ARGUMENT,
    ARCHITECTURE__GET_OPCODE_DETAILS__NOT_AN_OPCODE,
    ARCHITECTURE__GET_OPCODE_SIZE__NULL_ARGUMENT,
    ARCHITECTURE__IS_INSTRUCTION__NULL_ARGUMENT,
    ARCHITECTURE__IS_OPCODE__NULL_ARGUMENT,
    ARCHITECTURE__IS_REGISTER__NULL_ARGUMENT,
    ARCHITECTURE__GET_REGISTER_VALUE__NULL_ARGUMENT,
    ARCHITECTURE__GET_REGISTER_VALUE__INVALID_REGISTER_MAME,
    LINE_PARSER__PARSE_DATA_NUMBERS__NULL_ARGUMENT,
    LINE_PARSER__PARSE_DATA_NUMBERS__NO_DATA_VALUES,
    LINE_PARSER__PARSE_DATA_NUMBERS__ALLOCATION_ERROR,
    LINE_PARSER__PARSE_DATA_NUMBERS__INVALID_DATA_VALUE,
    LINE_PARSER__PARSE_LINE__NULL_ARGUMENT,
    LINE_PARSER__PARSE_LINE__LABEL_IN_ENTRY,
    LINE_PARSER__PARSE_LINE__LABEL_IN_EXTERN,
    LINE_PARSER__PARSE_LINE__TOO_LONG_OPCODE,
    LINE_PARSER__PARSE_LINE__INVALID_OPCDODE,
    LINE_PARSER__PARSE_LINE__ALLOCATION_ERROR,
    LINE_PARSER__PARSE_INSTRUCTION_OPERANDS__NULL_ARGUMENT,
    LINE_PARSER__PARSE_INSTRUCTION_OPERANDS__NO_COMMA_BETWEEN_OPERANDS,
    LINE_PARSER__PARSE_INSTRUCTION_OPERANDS__NO_OPERANDS_EXPECTED,
    LINE_PARSER__PARSE_INSTRUCTION_OPERANDS__ALLOCATION_ERROR,
    FIRST_PASS__PROCESS_INPUT_FILE__NULL_ARGUMENT,
    FIRST_PASS__PROCESS_INPUT_FILE__FILE_OPEN_ERROR,
    FIRST_PASS__PROCESS_INPUT_FILE__UNKNOWN_LINE_TYPE,
    FIRST_PASS__PROCESS_INPUT_FILE__FOUND_EXTERN_WITH_LABEL,
    FIRST_PASS__PROCESS_INPUT_FILE__INVALID_STRING,
    FIRST_PASS__DETECT_SYMBOLS_DUPLICATION__NULL_ARGUMENT,
    FIRST_PASS__DETECT_SYMBOLS_DUPLICATION__FOUND_DUPLICATION,
    FIRST_PASS__DETECT_ENTRIES_DUPLICATION__NULL_ARGUMENT,
    FIRST_PASS__DETECT_ENTRIES_DUPLICATION__FOUND_DUPLICATION,
    SECOND_PASS__ENCODE_LINE__NULL_ARGUMENT,
    SECOND_PASS__ENCODE_LINE__UNSOPPORTED_LINE_TYPE,
    SECOND_PASS__ENCODE_LINE__INVALID_LINE_TYPE,
    SECOND_PASS__FINALIZE_SYMBOL_TABLE__ENTRY_ON_EXTERN,
    SECOND_PASS__FINALIZE_SYMBOL_TABLE__SYMBOL_NOT_FOUND,
    SECOND_PASS__RESOLVE_OPERAND__NULL_ARGUMENT,
    SECOND_PASS__RESOLVE_OPERAND__UNRECOGNIZED_OPERAND,
    SECOND_PASS__RESOLVE_OPERAND__STRTOL_ERROR,
    SECOND_PASS__RESOLVE_OPERAND__LABEL_NOT_FOUND,
    SECOND_PASS_ENTER_NEW_EXTERN_USAGE__NULL_ARGUMENT,
    SECOND_PASS_ENTER_NEW_EXTERN_USAGE__REACHED_MAX_EXTERN_USAGES,
    SECOND_PASS__ENCODE_INSTRUCTION__NULL_ARGUMENT,
    SECOND_PASS__ENCODE_INSTRUCTION__FAILED_MALLOC,
    SECOND_PASS__ENCODE_INSTRUCTION__INVALID_OPERANDS_NUMBER,
    SECOND_PASS__ENCODE_INSTRUCTION__UNSOPPORTED_LINE_TYPE,
    SECOND_PASS__ENCODE_INSTRUCTION__INVALID_LINE_TYPE,
    SECOND_PASS__HANDLE_INSTRUCTION_OPERAND__NULL_ARGUMENT,
    SECOND_PASS__HANDLE_INSTRUCTION_OPERAND__UNSUPPORTED_OPERAND_TYPE,
    SECOND_PASS__PROCESS__NULL_ARGUMENT
} RC_t;

#define EXIT_ON_ERROR(function_output, return_code) do {    \
    int rc = (function_output);                             \
    *(return_code) = rc;                                    \
    if (rc != 0) {                                          \
        goto Exit;                                          \
    }                                                       \
} while (0)

#define EXIT_IF_NULL(value, rc) do {                       \
    if (value == NULL) {                                   \
        return_code = rc;                                  \
        goto Exit;                                         \
    }                                                      \
} while (0)

#define MAX_LINE_LENGTH 100
#define MAX_FILE_PATH_LENGTH 256
#define MAX_LINES_IN_FILE 1024